package com.dangkang.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dangkang.cbrn.db.ChemicalInfo;
import com.dangkang.cbrn.db.DeviceInfo;
import com.dangkang.cbrn.db.TaintInfo;
import com.dangkang.cbrn.db.TypeInfo;

import com.dangkang.db.ChemicalInfoDao;
import com.dangkang.db.DeviceInfoDao;
import com.dangkang.db.TaintInfoDao;
import com.dangkang.db.TypeInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chemicalInfoDaoConfig;
    private final DaoConfig deviceInfoDaoConfig;
    private final DaoConfig taintInfoDaoConfig;
    private final DaoConfig typeInfoDaoConfig;

    private final ChemicalInfoDao chemicalInfoDao;
    private final DeviceInfoDao deviceInfoDao;
    private final TaintInfoDao taintInfoDao;
    private final TypeInfoDao typeInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chemicalInfoDaoConfig = daoConfigMap.get(ChemicalInfoDao.class).clone();
        chemicalInfoDaoConfig.initIdentityScope(type);

        deviceInfoDaoConfig = daoConfigMap.get(DeviceInfoDao.class).clone();
        deviceInfoDaoConfig.initIdentityScope(type);

        taintInfoDaoConfig = daoConfigMap.get(TaintInfoDao.class).clone();
        taintInfoDaoConfig.initIdentityScope(type);

        typeInfoDaoConfig = daoConfigMap.get(TypeInfoDao.class).clone();
        typeInfoDaoConfig.initIdentityScope(type);

        chemicalInfoDao = new ChemicalInfoDao(chemicalInfoDaoConfig, this);
        deviceInfoDao = new DeviceInfoDao(deviceInfoDaoConfig, this);
        taintInfoDao = new TaintInfoDao(taintInfoDaoConfig, this);
        typeInfoDao = new TypeInfoDao(typeInfoDaoConfig, this);

        registerDao(ChemicalInfo.class, chemicalInfoDao);
        registerDao(DeviceInfo.class, deviceInfoDao);
        registerDao(TaintInfo.class, taintInfoDao);
        registerDao(TypeInfo.class, typeInfoDao);
    }
    
    public void clear() {
        chemicalInfoDaoConfig.clearIdentityScope();
        deviceInfoDaoConfig.clearIdentityScope();
        taintInfoDaoConfig.clearIdentityScope();
        typeInfoDaoConfig.clearIdentityScope();
    }

    public ChemicalInfoDao getChemicalInfoDao() {
        return chemicalInfoDao;
    }

    public DeviceInfoDao getDeviceInfoDao() {
        return deviceInfoDao;
    }

    public TaintInfoDao getTaintInfoDao() {
        return taintInfoDao;
    }

    public TypeInfoDao getTypeInfoDao() {
        return typeInfoDao;
    }

}
